#!/usr/bin/env python3

import sys, math, time
from sys import stdin
from math import factorial, sqrt, exp, floor
from datetime import datetime, timedelta


def print_help():
    print("USAGE")
    print("\t./204ducks a")
    print("DESCRIPTION")
    print("\ta constant")

def error_handling():
    if len(sys.argv) != 2 or '-h' in sys.argv or '--help' in sys.argv:
        print_help()
        sys.exit(84)
    try:
        first = float(sys.argv[1])
    except:
        print_help()
        sys.exit(84)
    if (first < 0):
        sys.exit(84)
    return first

def average_time(a):
    tab = []
    res = (3 * ( a + 2)) / 8
    min = floor(res)
    sec = (res - min) * 60
    tab.append(min)
    tab.append(sec)
    return tab

def main():
    arg = error_handling()
    tab = average_time(arg)
    print(tab)

main()
