#!/usr/bin/env python3

import sys, math, time
from sys import stdin

def print_help():
    print("USAGE")
    print("\t./204ducks a")
    print("DESCRIPTION")
    print("\ta constant")

def main():
    if len(sys.argv) != 2 or '-h' in sys.argv or '--help' in sys.argv:
        print_help()
        sys.exit(84)
    try:
        first = float(sys.argv[1])
    except:
        print_help();
        sys.exit(84)



main()
